#
# Documentation of the Visor REST Api
#
swagger: '2.0'

# Document Metadata
info:
  version: "0.2.0"
  title: Visor REST Api
  contact:
    name: Daniel Baur
    email: daniel.baur@uni-ulm.de
    url: http://github.com/cloudiator/visor
  license:
    name: Apache License 2.0
    url: https://raw.githubusercontent.com/cloudiator/visor/master/LICENSE
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

host: localhost:31415

parameters:
  uuid:
    name: uuid
    in: path
    description: A globally unique identifier of a monitor.
    required: true
    type: string

definitions:

  Monitor:
    type: object
    required:
      - metricName
      - componentId
      - type
    discriminator: type
    properties:
      type:
        type: string
        enum: ['PushMonitor','SensorMonitor']
      metricName:
        type: string
        description: "Unique name identifying the metric"
      componentId:
        type: string
        description: "ID of the component monitored by this sensor."
      monitorContext:
        type: object
        description: "Context of the monitor. Multiple key - value pairs depicting the environment of the monitor."
        additionalProperties:
          type: string

  PushMonitor:
    description: "A monitoring providing a telnet endpoint where applications can advertise metrics."
    allOf:
      - $ref: '#/definitions/Monitor'
      - type: object
        properties:
          port:
            type: number
            format: int32

  SensorMonitor:
    allOf:
      - $ref: '#/definitions/Monitor'
      - type: object
        required:
          - sensorClassName
          - interval
        properties:
          sensorClassName:
            type: string
          interval:
            $ref: '#/definitions/Interval'
          sensorConfiguration:
            type: object
            additionalProperties:
              type: string

  Interval:
    type: object
    required:
      - period
      - timeUnit
    properties:
      period:
        type: number
        format: int64
      timeUnit:
        type: string
        enum: ['NANOSECONDS','MICROSECONDS','MILLISECONDS','SECONDS','MINUTES','HOURS','DAYS']

paths:
  /monitors:
    get:
      operationId: getMonitors
      responses:
        200:
         description: 'OK'
         schema:
           type: array
           items:
             $ref: '#/definitions/Monitor'

    post:
      operationId: postMonitors
      parameters:
        - name: monitor
          in: body
          required: true
          schema:
            $ref: '#/definitions/Monitor'
      responses:
        200:
          description: 'OK'
          schema:
            $ref: '#/definitions/Monitor'

    delete:
      operationId: deleteMonitors
      responses:
        200:
          description: 'OK'



  /monitors/{uuid}:
    get:
      operationId: getMonitor
      parameters:
        - $ref: '#/parameters/uuid'
      responses:
        200:
          description: 'OK'
          schema:
            $ref: '#/definitions/Monitor'

    put:
      operationId: putMonitor
      parameters:
        - $ref: '#/parameters/uuid'
      responses:
        200:
          description: 'OK'
          schema:
            $ref: '#/definitions/Monitor'

    delete:
      operationId: deleteMonitor
      parameters:
        - $ref: '#/parameters/uuid'
      responses:
        200:
          description: 'OK'





